# Generated by Django 3.2.9 on 2023-07-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(max_length=2048, verbose_name='内容')),
                ('user', models.IntegerField(verbose_name='所属用户id')),
                ('publishDate', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('category', models.SmallIntegerField(choices=[(1, '公告'), (2, '推荐'), (3, '最新'), (4, '热门')], default=3, verbose_name='所属板块')),
                ('status', models.SmallIntegerField(choices=[(1, '待审核'), (2, '审核通过'), (4, '已删除'), (3, '审核未通过')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='ForumComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='所属用户id')),
                ('content', models.TextField(max_length=1024, verbose_name='内容')),
                ('publishDate', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('passage_id', models.IntegerField(verbose_name='所属帖子id')),
                ('status', models.SmallIntegerField(choices=[(1, '待审核'), (2, '审核通过'), (4, '已删除'), (3, '审核未通过')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.CharField(max_length=64, verbose_name='版本号')),
                ('publishTime', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('substance', models.CharField(max_length=1024, verbose_name='内容')),
                ('developer', models.SmallIntegerField(choices=[(1, 'wezy'), (2, 'qldyd'), (3, 'wezy&qldyd')], default=1, verbose_name='开发者')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='用户名')),
                ('email', models.CharField(max_length=128, verbose_name='邮箱')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('if_write_off', models.SmallIntegerField(choices=[(1, '已注销'), (2, '未注销')], default=2, verbose_name='是否已经注销')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='上次登录时间')),
            ],
        ),
    ]
