# Generated by Django 3.2.9 on 2023-07-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20230730_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='status',
            field=models.SmallIntegerField(choices=[(3, '审核未通过'), (2, '审核通过'), (4, '已删除'), (1, '待审核')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='forumcomments',
            name='status',
            field=models.SmallIntegerField(choices=[(3, '审核未通过'), (2, '审核通过'), (4, '已删除'), (1, '待审核')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='log',
            name='publishTime',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
