# Generated by Django 3.2.9 on 2023-07-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20230730_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待审核'), (3, '审核未通过'), (4, '已删除'), (2, '审核通过')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='forumcomments',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待审核'), (3, '审核未通过'), (4, '已删除'), (2, '审核通过')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='log',
            name='publishTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
